appserver/config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  resources :indicators, only: %i(index show)
  namespace :api, format: "json" do
    resources :indicators, only: %i(index)
  end
  get 'additionals', to: 'indicators#additionals'
  get 'tos', to: 'welcome#tos'
end

appserver/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

appserver/app/models/indicator.rb
# frozen_string_literal: true

class Indicator < ApplicationRecord
  scope :filter_by_symbols, lambda { |symbols|
    where(symbol: symbols) unless symbols.nil?
  }

  scope :filter_by_price, lambda { |price|
    where(price: price[:lower]..price[:upper])
  }

  scope :filter_by_probability, lambda { |probability|
    where(
      probability_short: probability[:short][:lower]..probability[:short][:upper],
      probability_medium: probability[:medium][:lower]..probability[:medium][:upper],
      probability_long: probability[:long][:lower]..probability[:long][:upper]
    )
  }

  scope :filter_by_myuhat, lambda { |myuhat|
    where(
      myuhat_short: myuhat[:short][:lower]..myuhat[:short][:upper],
      myuhat_medium: myuhat[:medium][:lower]..myuhat[:medium][:upper],
      myuhat_long: myuhat[:long][:lower]..myuhat[:long][:upper]
    )
  }

  scope :filter_by_sigmahat, lambda { |sigmahat|
    where(
      sigmahat_short: sigmahat[:short][:lower]..sigmahat[:short][:upper],
      sigmahat_medium: sigmahat[:medium][:lower]..sigmahat[:medium][:upper],
      sigmahat_long: sigmahat[:long][:lower]..sigmahat[:long][:upper]
    )
  }

  scope :filter_by, lambda { |symbols, price, probability, myuhat, sigmahat|
    filter_by_symbols(symbols).filter_by_price(price)
                              .filter_by_probability(probability)
                              .filter_by_myuhat(myuhat)
                              .filter_by_sigmahat(sigmahat)
  }

  def round
    indicators = {}
    indicators['id'] = id
    indicators['symbol'] = symbol
    indicators['price'] = price
    indicators['probability_short'] = probability_short.round(4)
    indicators['myuhat_short'] = myuhat_short.round(4)
    indicators['sigmahat_short'] = sigmahat_short.round(4)
    indicators['probability_medium'] = probability_medium.round(4)
    indicators['myuhat_medium'] = myuhat_medium.round(4)
    indicators['sigmahat_medium'] = sigmahat_medium.round(4)
    indicators['probability_long'] = probability_long.round(4)
    indicators['myuhat_long'] = myuhat_long.round(4)
    indicators['sigmahat_long'] = sigmahat_long.round(4)
    indicators
  end
end

appserver/app/controllers/api/indicators_controller.rb
# frozen_string_literal: true

class API::IndicatorsController < ApplicationController
  def index
    @all_indicators = Indicator.filter_by(symbols, price, probability, myuhat, sigmahat)
                               .order(:symbol)
                               .map(&:round)
  end

  private

  def symbols
    params[:symbol].nil? ? nil : params[:symbol].split(',')
  end

  def price
    {
      lower: params[:price_lowervalue],
      upper: params[:price_uppervalue]
    }
  end

  def probability
    {
      short: {
        lower: params[:probability_short_lowervalue],
        upper: params[:probability_short_uppervalue]
      },
      medium: {
        lower: params[:probability_medium_lowervalue],
        upper: params[:probability_medium_uppervalue]
      },
      long: {
        lower: params[:probability_long_lowervalue],
        upper: params[:probability_long_uppervalue]
      }
    }
  end

  def myuhat
    {
      short: {
        lower: params[:myuhat_short_lowervalue],
        upper: params[:myuhat_short_uppervalue]
      },
      medium: {
        lower: params[:myuhat_medium_lowervalue],
        upper: params[:myuhat_medium_uppervalue]
      },
      long: {
        lower: params[:myuhat_long_lowervalue],
        upper: params[:myuhat_long_uppervalue]
      }
    }
  end

  def sigmahat
    {
      short: {
        lower: params[:sigmahat_short_lowervalue],
        upper: params[:sigmahat_short_uppervalue]
      },
      medium: {
        lower: params[:sigmahat_medium_lowervalue],
        upper: params[:sigmahat_medium_uppervalue]
      },
      long: {
        lower: params[:sigmahat_long_lowervalue],
        upper: params[:sigmahat_long_uppervalue]
      }
    }
  end
end

appserver/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

appserver/app/controllers/indicators_controller.rb
# frozen_string_literal: true

class IndicatorsController < ApplicationController
  def index
    @update_at = Indicator.order(:update_at).last.update_at
  end

  def show
    @indicators = Indicator.find(params[:id])
  end

  def additionals; end
end

appserver/app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
  def tos; end
end

appserver/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # rubocop:disable Metrics/MethodLength
  def default_meta_tags
    {
      site: 'KabuCalculator',
      title: 'KabuCalculator',
      reverse: true,
      charset: 'utf-8',
      description: '統計指標に基づいた株式比較、抽出ツール',
      viewport: 'width=device-width, initial-scale=1.0',
      og: {
        title: :title,
        type: 'website',
        site_name: :site,
        description: :description,
        image: 'https://kabucalculator.ml/ogp/ogp.png',
        url: 'https://kabucalculator.ml/'
      },
      twitter: {
        title: :title,
        card: 'summary',
        site: '@kabucalculator',
        description: :description,
        image: 'https://kabucalculator.ml/ogp/ogp.png',
        domain: 'https://kabucalculator.ml/'
      }
    }
  end
  # rubocop:enable Metrics/MethodLength
end

appserver/app/views/indicators/additionals.html.slim
- content_for(:title, '補足説明')

.container
  #js-additionals-vue

appserver/app/views/indicators/index.html.slim
- content_for(:title, '指標一覧')
= stylesheet_pack_tag 'indicators/index'
.text-end.pe-5
  i.fa-solid.fa-arrows-rotate.pe-2
  | #{@update_at.strftime("%Y-%m-%d %H:%M") + ' データ更新'}
.container
  #js-indicators-vue

appserver/app/views/indicators/show.html.slim
- content_for(:title, @indicators.symbol + 'の将来価格予想')

.container
  #js-future-price-vue(data-vue-symbol="#{@indicators.symbol}" data-vue-last-price="#{@indicators.price}")

appserver/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) + ' | KabuCalculator' : 'KabuCalculator'
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = display_meta_tags default_meta_tags
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_pack_tag 'kabucalculator-favicon.ico'
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - unless current_page?(root_path)
      = render 'shared/header'
    = yield
    = render 'shared/footer'

appserver/app/views/shared/_footer.html.slim
footer
  div.text-center.py-2
    = link_to '利用規約', tos_path, class: 'tos'
    = link_to 'https://github.com/makiichikawa/kabucalculator' do
      i.fab.fa-github.social-link
    = link_to 'https://twitter.com/Ichikaw77248774' do
      i.fab.fa-twitter.social-link
  div.text-center
    = Time.current.year
    |  ©makiichikawa

appserver/app/views/shared/_header.html.slim
header
  nav.navbar.p-0.justify-content-end
    .navbar-brand.p-0.ml-auto
      = link_to indicators_path do
        = image_pack_tag('kabucalculator-logo-header.svg', alt: '株価統計指標サービス', class: 'header-image')

appserver/app/views/welcome/index.html.slim
.container
  #js-top-vue

appserver/app/views/welcome/tos.html.slim
- content_for(:title) { '利用規約' }

.container
  #js-terms-of-service-vue